### ISSUE TITLE
"Charms of ___" Compatibility with EnvironmentZ

### ISSUE THREAD

**Issue by IAmVensey** [TheWinABagel/Zenith#38]
Hello,

I am playing on a Medieval Minecraft server (fabric, Minecraft version 1.19.2, version 20.5) and the Charms of Hydration, Warming, and Cooling do not seem to be working. The Environmentz mod is enabled on this server, and it is version 2.0. The Lava Vision and other charms that do not interact with EnvironmentZ DO seem to work, so I'm not sure if this is just a compatibility issue between the two mods.

Any advice on how to get these working would be appreciated! Thank you for your hard work!

**Comment by TheWinABagel** [comment]
If you add
`minecraft:overheating_resistance
minecraft:cold_resistance
`
to your potion.cfg in the Zenith folder in your configs, under "Extended Potion Charms"
this *should* fix it

**Comment by muon-rw** [comment]
The above fix increases the duration for Heating and Cooling, but the `dehydration:hydration`/`minecraft:hydration` effect duration (tried both) doesn't seem to be increasing. 

Worth noting that the warming/cooling effect not working for @IAmVensey is probably largely due to modpack version - the effects needed to be configured via datapack which was done in a later modpack update (and later also in a new version of EnvironmentZ). 

The hydration effect though _does_ seem to just have its duration range increased, though.

**Comment by muon-rw** [comment]
Never mind, the proper effect id's are:

`environmentz:cooling`
`environmentz:warming`
`dehydration:hydration_effect`

But annoyingly, the hydration effect still doesn't apply in the extended range... ([Here's the effect, something about using a modulus based on effect amplification to determine when to apply it, unfortunately I can't read java](https://github.com/Globox1997/Dehydration/blob/1.20/src/main/java/net/dehydration/effect/HydrationEffect.java))

And neither the regular or extended durations apply the effect constantly. But using the extended duration and turning it off _will_ pass over remaining duration ammounts that apply the effect and it will restore some thirst as it times out.
